"use client";
import { useState } from 'react';
export type BuilderJob={id:string;kind:string;status:string;progress:string;error:string|null;attempts:number;revision:number};
export type Metric={day:string;page:string;views:number};
export type DomainStatus={verified?:boolean;ownershipVerified?:boolean;misconfigured?:boolean;verification?:{type:string;domain:string;value:string}[];recommendedIPv4?:{rank:number;value:string[]}[];recommendedCNAME?:{rank:number;value:string}[]};
export default function BuilderRelease({jobs,metrics,enquiries,domain,status,busy,published,onAction}:{jobs:BuilderJob[];metrics:Metric[];enquiries:number;domain:string|null;status:DomainStatus|null;busy:boolean;published:boolean;onAction:(action:string,extra?:Record<string,unknown>,label?:string)=>Promise<void>}) {
  const [name,setName]=useState('');
  return <section className="wb-release" aria-label="Website operations">
    <div className="wb-two"><div><h3>Background jobs</h3><p className="wb-help">You can close the browser after a job is queued. Its progress and errors are saved here.</p>{jobs.length===0?<p>No operations yet.</p>:<ol className="wb-jobs">{jobs.slice(0,5).map(job=><li key={job.id}><strong>{job.kind} · Draft {job.revision}</strong><span role={['running','waiting','queued'].includes(job.status)?'status':undefined}>{job.progress} · {job.status}</span>{job.error&&<small className="wb-alert">{job.error}</small>}</li>)}</ol>}</div>
    <div><h3>Website results</h3><p><strong>{metrics.reduce((sum,m)=>sum+Number(m.views),0).toLocaleString()}</strong> page views · last 30 days</p><p><strong>{enquiries}</strong> enquiries received · all time</p><p className="wb-help">Enquiries appear in the CRM pipeline as New, with this website and client attached. Page views are aggregate counts, not unique visitors; preview visits are excluded.</p><ul>{['home','about','services','contact'].map(page=><li key={page}>{page}: {metrics.filter(m=>m.page===page).reduce((sum,m)=>sum+Number(m.views),0).toLocaleString()} views</li>)}</ul></div></div>
    <details className="wb-infrastructure"><summary>Custom domain & DNS</summary><p>Publish and test the website first. Add only a domain you own; this never changes the CRM or HBS marketing domain.</p>{domain?<><p><strong>{domain}</strong> · {status?.verified?'DNS configured; Vercel manages HTTPS':'Setup needs attention'}</p><button disabled={busy} onClick={()=>onAction('domain-check',{},'Checking domain ownership and DNS…')}>Recheck DNS</button><button disabled={busy} onClick={()=>onAction('domain-add',{domain},'Retrying domain connection…')}>Retry connection</button>{status?.verification?.map((item,index)=><p key={index}>Ownership record: {item.type} · <code>{item.domain}</code> → <code>{item.value}</code></p>)}{status?.recommendedCNAME?.filter(r=>r.rank===1).map((item,index)=><p key={index}>Recommended CNAME: <code>{domain}</code> → <code>{item.value}</code></p>)}{status?.recommendedIPv4?.filter(r=>r.rank===1).map((item,index)=><p key={index}>Recommended A record: <code>{domain}</code> → <code>{item.value.join(', ')}</code></p>)}<p className="wb-help">Use the applicable CNAME or A record at your domain provider, not both at the same name. Preserve email/MX records. DNS can take time to update. Confirm the site opens over HTTPS before sharing its domain.</p></>:<div className="wb-actions"><label className="wb-field">Domain name<input value={name} maxLength={253} placeholder="www.yourbusiness.co.uk" onChange={e=>setName(e.target.value)} /></label><button disabled={busy||!published||!name.trim()} onClick={()=>{if(window.confirm(`Connect ${name} to this website? Only proceed if you own this domain and intend to point it to this website.`))void onAction('domain-add',{domain:name},'Connecting your domain…');}}>Connect domain</button></div>}</details>
  </section>;
}
